name: Threadder deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install packages
        run: yarn
      - name: Delpoy new version
        run: yarn deploy
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}