name: Threadder deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install packages
        run: yarn
      - name: Build new version
        run: yarn build
      - name: Deploy new version
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn run gh-pages -d build -u "Abdelrahman <said.abdelrahman89@gmail.com>"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}