name: Threadder deploy
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        - name: Setup node.js
          uses: actions/setup-node@v1
          with:
            node-version: 14
      - name: Install packages
        run: yarn
        - name: Deploy
          run: yarn deploy